# 2.1.Extraction d'un fichier csv

## Import libraries

In [1]:
import pandas as pd

## Extract from CSV file

In [2]:
brevets = pd.read_csv('/Users/juliensisavath2017/THP_loc/THP-2/S05/1/2.SourceDB/2.1_CSV-Extract/fr-esr-brevets-france-inpi-oeb.csv', sep = ";", encoding = 'utf-8')
brevets

,num_depot,origine,annees_publication,annees_delivrance,part,type_d_tablissement,num_siren,id_dep,com_code,com_nom,...,type,etab,domaine_technologique,sous_domaine_technologique,nom,brev_de,de_libelle,de_sd1_libelle,de_sd2_libelle,fe_id
0,1161944,France,2013,2013.0,Non,Grande Entreprise (GE),632012100,49478,75108,Paris 8e,...,Personne morale,Grande Entreprise (GE),Chimie,Chimie organique fine,L'oreal,Non,NaN,NaN,NaN,FE1
1,0400729,France,2005,2006.0,Non,Personne physique,NaN,12620,35238,Rennes,...,Personne physique,Personne physique,Chimie,Chimie alimentaire,delerue,Non,NaN,NaN,NaN,FE1
2,0512601,France,2007,NaN,Non,Personne physique,NaN,15837,91477,Palaiseau,...,Personne physique,Personne physique,"Electronique, électricité",Transmission d’informations numériques,gauthier,Oui,TIC,Télécommunications,NaN,FE1
3,1150006,France,2012,2014.0,Non,Personne physique;Personne physique,NaN,489;7548,"69034,69034","Caluire-et-Cuire,Caluire-et-Cuire",...,Personne physique;Personne physique,Personne physique;Personne physique,Autres,BTP,BERNARD;bernard,Non,NaN,NaN,NaN,FE1
4,1101373,France,2012,2014.0,Non,Entreprise de taille Intermédiaire (ETI),394342299,37732,94021,Chevilly-Larue,...,Personne morale,Entreprise de taille Intermédiaire (ETI),Instrumentation,Techniques de mesure,Aer,Oui,TIC,Autres TIC,NaN,FE1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
222622,0402041,France,2005,NaN,Non,Personne physique,NaN,27732,74183,Mieussy,...,Personne physique,Personne physique,"Machines, mécanique, transports",Composants mécaniques,saunion,Non,NaN,NaN,NaN,FE1
222623,0402056,France,2005,2007.0,Non,Petite et Moyenne Entreprise (PME),781229406,50602,16113,La Couronne,...,Personne morale,Petite et Moyenne Entreprise (PME),Autres,BTP,Ets A Deschamps Et Fils,Non,NaN,NaN,NaN,FE1
222624,1058214,France,2012,2013.0,Non,Entreprise,365501089,35718,76481,Octeville-sur-Mer,...,Personne morale,Entreprise,"Machines, mécanique, transports",Autres machines spécialisées,Sidel Participations,Non,NaN,NaN,NaN,FE1
222625,1158228,France,2013,2014.0,Non,Grande Entreprise (GE),780129987,50585,92012,Boulogne-Billancourt,...,Personne morale,Grande Entreprise (GE),"Electronique, électricité","Machines et appareils électriques, énergie éle...",Renault Sas,Non,NaN,NaN,NaN,FE1
222626,0402205,France,2005,2006.0,Non,Entreprise,424672665,41041,92023,Clamart,...,Personne morale;Personne morale,Entreprise;Entreprise,Instrumentation;Chimie,Techniques de mesure;Génie chimique,Bionisis Sa;Bionisis Sa,Oui,TIC,Autres TIC,NaN,FE1

## How many Brevets request we have

In [3]:
len(brevets)

222627

In [4]:
len(brevets[brevets['brev_de'].str.startswith('Oui')])

77705

### Based on 222'627 schools, there are 77'705 requests